### ISSUE TITLE
Country flag

### ISSUE THREAD

**Issue by YSDC** [hbb20/AndroidCountryPicker#27]
Hello,
I like your library, and I want to use it, but I struggle on how to display a different flag than `R.drawable.ic_flag_black`. 

I tried to look on how to get the emoji flag, but the issue is also that the `getFlag(alpha2Code: String)` expect an Int and therefore I don't know how to return the correct flag based on the user selection..

any help is welcome.

**Comment by hbb20** [comment]
Emoji flags are default flags which are in-built. Nothing need to be
changed. The custom flag provider is the if someone wants to provide flag
drawable and that int is drawable res id.

If emoji flag is not coming up by default, show me the code and will figure
it out.

**Comment by YSDC** [comment]
Thank you for your quick answer.
I looked at your sample with the "dropdown" to select the country, and I try to understand how can I display the emoji country flag instead of the default black flag (if you know what I mean.

**Comment by hbb20** [comment]
Aah. I see.. I was testing if I provide a custom flag then custom flag will
override the emoji flag. Try to remove that override in kotlin flow and it
should be back to emoji flag.

Simply remove line 29-32 of MainActivity.kt and re-run.

**Comment by hbb20** [comment]
*Line 29-34
