### ISSUE TITLE
Runtime error with context.launchCountry { }

### ISSUE THREAD

**Issue by Dave181295** [hbb20/AndroidCountryPicker#36]
Cannot access class 'com.hbb20.contrypicker.flagprovider.CPFlagProvider'. Check your module classpath for missing or conflicting dependencies

**Comment by Dave181295** [comment]
It's coming from here 

`    cpFlagProvider: [ERROR : com.hbb20.contrypicker.flagprovider.CPFlagProvider]?,`

**Comment by hbb20** [comment]
Please use v0.0.3. There are something I need to fix for flag provider

**Comment by Dave181295** [comment]
Thanks sir !

**Comment by Dave181295** [comment]
So for now, I can't use the flags ? so dialog is showing with only text..

**Comment by hbb20** [comment]
For now you can use emoji flags and if you have your own flag images then you can also pass that. I am in process of providing other flag packs to set different flag images (as different library) without increasing default library size.

**Comment by hbb20** [comment]
0.0.3 should work just fine with default emoji flags as shown in samples of documentation.

**Comment by Dave181295** [comment]
Hmm...
I'm trying 

`  requireContext().launchCountryPickerDialog(
                                customMasterCountries = "HE,RU,EN,FR",
                                "",
                                CPFileReader,
                                false,
                                null, null, { country -> country.name },
                                null, null,
                                null, CPDialogConfig.defaultCPDialogViewIds,
                                allowSearch = false,
                                allowClearSelection = false,
                                showTitle = true,
                                showFullScreen = false,
                            ) { cpCountry ->`

But there is no flags friend..

**Comment by hbb20** [comment]
You are passing 6th param (which is for flag provider) as null that tells to remove all flags. 

Either pass CPRowConfig.defaultFlagProvider (which is default emoji flag provider) as 6th argument
or ideally pass only named argument of params that you want to override. Library will provider defaults for other.

**Comment by Dave181295** [comment]
Thanks , where can I see the languages your library support?

**Comment by hbb20** [comment]
This library only support two languages as of now. English and Gujarati. I have other translations available but need some help to get other message translations. Are you in need of some specific language?
<img width="479" alt="image" src="https://user-images.githubusercontent.com/4918760/127751183-68363bb2-c657-4414-a33b-da7d83a91150.png">

**Comment by Dave181295** [comment]
By the way can you add a property for the country.language ? like English,French,etc.. 
Thanks a lot !

**Comment by Dave181295** [comment]
No worries, where can I find the strings to override these ?

**Comment by hbb20** [comment]
These two files contains all the strings resources. You can override as you need.
https://github.com/hbb20/AndroidCountryPicker/tree/develop/countrypicker/src/main/res/values-en

**Comment by hbb20** [comment]
Can you please explain what is your use case with country.language?

**Comment by Dave181295** [comment]
I'm using your library for my traduction's app. so it's more important to me to get the language  + the country but that not really a big  problem so all is okay :)

**Comment by Dave181295** [comment]
Hmm.. by the way I chose not to make full screen, but the dialog is still all the screen with 4 countries lol, maybe a bug ?

**Comment by Dave181295** [comment]
> Hmm.. by the way I chose not to make full screen, but the dialog is still all the screen with 4 countries lol, maybe a bug ?

Okay I just realized, so the showFullScreen doesn't make the dialog WRAP_CONTENT it's still very large and going until the bottom of the screen even if I have fews countries..

**Comment by hbb20** [comment]
yeah.. I want to make it wrap content but haven't finalized when should it be wrap_content. Hopefully that will be fixed soon.

**Comment by hbb20** [comment]
@Dave181295 , v0.0.6 has wrapping functionality. Let me know if that works for you.
