### ISSUE TITLE
Adding a library changes the name of my app

### ISSUE THREAD

**Issue by ivanBabiichuk** [hbb20/AndroidCountryPicker#52]
When I add the library, my app name changes to "CountryPicker".
I use lib version 0.0.7
How can this be fixed?

**Comment by hbb20** [comment]
I need to check this. Sorry about that.

**Comment by hbb20** [comment]
Fixed it in my code so newer version wont have this issue. For older versions, this can be helpful. https://stackoverflow.com/questions/42372876/app-name-was-overrided-by-library
